"""duels and friends

Revision ID: 4bea3d452f53
Revises: a9deb37c6bd8
Create Date: 2026-06-26 11:02:34.931916
"""
from alembic import op
import sqlalchemy as sa


revision = '4bea3d452f53'
down_revision = 'a9deb37c6bd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('addressee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['user.id'], name=op.f('fk_friendship_addressee_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], name=op.f('fk_friendship_requester_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friendship')),
    sa.UniqueConstraint('requester_id', 'addressee_id', name=op.f('uq_friendship_requester_id'))
    )
    op.create_index(op.f('ix_friendship_addressee_id'), 'friendship', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friendship_requester_id'), 'friendship', ['requester_id'], unique=False)
    op.create_table('duel',
    sa.Column('subject_version_id', sa.Uuid(), nullable=False),
    sa.Column('challenger_id', sa.Uuid(), nullable=False),
    sa.Column('opponent_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('challenger_material_id', sa.Uuid(), nullable=True),
    sa.Column('opponent_material_id', sa.Uuid(), nullable=True),
    sa.Column('first_user_id', sa.Uuid(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('phase_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('challenger_points', sa.Integer(), nullable=False),
    sa.Column('opponent_points', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Uuid(), nullable=True),
    sa.Column('forfeited_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenger_id'], ['user.id'], name=op.f('fk_duel_challenger_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['challenger_material_id'], ['material.id'], name=op.f('fk_duel_challenger_material_id_material'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opponent_id'], ['user.id'], name=op.f('fk_duel_opponent_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opponent_material_id'], ['material.id'], name=op.f('fk_duel_opponent_material_id_material'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], name=op.f('fk_duel_subject_version_id_subject_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duel'))
    )
    op.create_index(op.f('ix_duel_challenger_id'), 'duel', ['challenger_id'], unique=False)
    op.create_index(op.f('ix_duel_opponent_id'), 'duel', ['opponent_id'], unique=False)
    op.create_index(op.f('ix_duel_status'), 'duel', ['status'], unique=False)
    op.create_table('duel_round',
    sa.Column('duel_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('asker_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('challenger_answer', sa.Text(), nullable=False),
    sa.Column('opponent_answer', sa.Text(), nullable=False),
    sa.Column('challenger_answered', sa.Boolean(), nullable=False),
    sa.Column('opponent_answered', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('challenger_delta', sa.Integer(), nullable=False),
    sa.Column('opponent_delta', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asker_id'], ['user.id'], name=op.f('fk_duel_round_asker_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duel_id'], ['duel.id'], name=op.f('fk_duel_round_duel_id_duel'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duel_round'))
    )
    op.create_index(op.f('ix_duel_round_duel_id'), 'duel_round', ['duel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duel_round_duel_id'), table_name='duel_round')
    op.drop_table('duel_round')
    op.drop_index(op.f('ix_duel_status'), table_name='duel')
    op.drop_index(op.f('ix_duel_opponent_id'), table_name='duel')
    op.drop_index(op.f('ix_duel_challenger_id'), table_name='duel')
    op.drop_table('duel')
    op.drop_index(op.f('ix_friendship_requester_id'), table_name='friendship')
    op.drop_index(op.f('ix_friendship_addressee_id'), table_name='friendship')
    op.drop_table('friendship')
    # ### end Alembic commands ###
