"""chat soft delete + subject icon

Revision ID: 51a970b09824
Revises: 6f21f9a05b29
Create Date: 2026-06-26 11:52:52.019637
"""
from alembic import op
import sqlalchemy as sa


revision = '51a970b09824'
down_revision = '6f21f9a05b29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('icon', sa.String(length=16), nullable=False, server_default=''))
    op.alter_column('subject', 'icon', server_default=None)  # keep default app-side only
    op.add_column('tutor_session', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tutor_session_deleted_at'), 'tutor_session', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_session_deleted_at'), table_name='tutor_session')
    op.drop_column('tutor_session', 'deleted_at')
    op.drop_column('subject', 'icon')
    # ### end Alembic commands ###
