"""login_attempt throttle

Revision ID: 6f21f9a05b29
Revises: 4bea3d452f53
Create Date: 2026-06-26 11:47:13.736858
"""
from alembic import op
import sqlalchemy as sa


revision = '6f21f9a05b29'
down_revision = '4bea3d452f53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempt',
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempt'))
    )
    op.create_index('ix_login_attempt_ip_created', 'login_attempt', ['ip', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempt_ip_created', table_name='login_attempt')
    op.drop_table('login_attempt')
    # ### end Alembic commands ###
