"""baseline

Revision ID: a9deb37c6bd8
Revises: 
Create Date: 2026-06-25 16:17:59.293921
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a9deb37c6bd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank_tier',
    sa.Column('profile_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('ep', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rank_tier')),
    sa.UniqueConstraint('profile_key', 'name', name=op.f('uq_rank_tier_profile_key'))
    )
    op.create_index(op.f('ix_rank_tier_profile_key'), 'rank_tier', ['profile_key'], unique=False)
    op.create_table('season',
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season'))
    )
    op.create_index(op.f('ix_season_key'), 'season', ['key'], unique=False)
    op.create_table('subject',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject'))
    )
    op.create_index(op.f('ix_subject_key'), 'subject', ['key'], unique=True)
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('background', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('progression_event',
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_progression_event_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progression_event'))
    )
    op.create_index(op.f('ix_progression_event_seq'), 'progression_event', ['seq'], unique=False)
    op.create_index(op.f('ix_progression_event_subject_id'), 'progression_event', ['subject_id'], unique=False)
    op.create_index(op.f('ix_progression_event_user_id'), 'progression_event', ['user_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_refresh_token_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token'))
    )
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('subject_version',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('pack_schema_version', sa.String(length=16), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('progression_profile', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_subject_version_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_version')),
    sa.UniqueConstraint('subject_id', 'version', name=op.f('uq_subject_version_subject_id'))
    )
    op.create_index(op.f('ix_subject_version_subject_id'), 'subject_version', ['subject_id'], unique=False)
    op.create_table('usage_event',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=48), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_micro_eur', sa.BigInteger(), nullable=False),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_usage_event_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_event'))
    )
    op.create_index(op.f('ix_usage_event_user_id'), 'usage_event', ['user_id'], unique=False)
    op.create_table('user_subject_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=32), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_subject_progress_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subject_id', 'season_id', name=op.f('pk_user_subject_progress'))
    )
    op.create_table('concept',
    sa.Column('subject_version_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('misconceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tutor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], name=op.f('fk_concept_subject_version_id_subject_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept')),
    sa.UniqueConstraint('subject_version_id', 'key', name=op.f('uq_concept_subject_version_id'))
    )
    op.create_index(op.f('ix_concept_key'), 'concept', ['key'], unique=False)
    op.create_index(op.f('ix_concept_subject_version_id'), 'concept', ['subject_version_id'], unique=False)
    op.create_table('practice_session',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_version_id', sa.Uuid(), nullable=False),
    sa.Column('focus_concept_id', sa.Uuid(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], name=op.f('fk_practice_session_subject_version_id_subject_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_practice_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_session'))
    )
    op.create_index(op.f('ix_practice_session_user_id'), 'practice_session', ['user_id'], unique=False)
    op.create_table('rubric',
    sa.Column('subject_version_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], name=op.f('fk_rubric_subject_version_id_subject_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubric')),
    sa.UniqueConstraint('subject_version_id', 'key', name=op.f('uq_rubric_subject_version_id'))
    )
    op.create_index(op.f('ix_rubric_subject_version_id'), 'rubric', ['subject_version_id'], unique=False)
    op.create_table('test',
    sa.Column('subject_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('teacher_approved', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_test_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], name=op.f('fk_test_subject_version_id_subject_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test'))
    )
    op.create_index(op.f('ix_test_subject_version_id'), 'test', ['subject_version_id'], unique=False)
    op.create_table('concept_closure',
    sa.Column('ancestor_id', sa.Uuid(), nullable=False),
    sa.Column('descendant_id', sa.Uuid(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ancestor_id'], ['concept.id'], name=op.f('fk_concept_closure_ancestor_id_concept'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descendant_id'], ['concept.id'], name=op.f('fk_concept_closure_descendant_id_concept'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ancestor_id', 'descendant_id', name=op.f('pk_concept_closure'))
    )
    op.create_table('concept_edge',
    sa.Column('subject_version_id', sa.Uuid(), nullable=False),
    sa.Column('parent_concept_id', sa.Uuid(), nullable=False),
    sa.Column('child_concept_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['child_concept_id'], ['concept.id'], name=op.f('fk_concept_edge_child_concept_id_concept'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_concept_id'], ['concept.id'], name=op.f('fk_concept_edge_parent_concept_id_concept'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], name=op.f('fk_concept_edge_subject_version_id_subject_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_concept_id', 'child_concept_id', name=op.f('pk_concept_edge'))
    )
    op.create_index(op.f('ix_concept_edge_subject_version_id'), 'concept_edge', ['subject_version_id'], unique=False)
    op.create_table('material',
    sa.Column('subject_version_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('teacher_approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_material_concept_id_concept'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_material_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], name=op.f('fk_material_subject_version_id_subject_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material'))
    )
    op.create_index(op.f('ix_material_concept_id'), 'material', ['concept_id'], unique=False)
    op.create_index(op.f('ix_material_subject_version_id'), 'material', ['subject_version_id'], unique=False)
    op.create_table('practice_item',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('question_template_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_practice_item_concept_id_concept'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['practice_session.id'], name=op.f('fk_practice_item_session_id_practice_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_item'))
    )
    op.create_index(op.f('ix_practice_item_session_id'), 'practice_item', ['session_id'], unique=False)
    op.create_table('user_concept_mastery',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('mastery', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_user_concept_mastery_concept_id_concept'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_concept_mastery_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'concept_id', name=op.f('pk_user_concept_mastery'))
    )
    op.create_table('answer',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grade', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('graded_by', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['practice_item.id'], name=op.f('fk_answer_item_id_practice_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_answer_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer'))
    )
    op.create_index(op.f('ix_answer_item_id'), 'answer', ['item_id'], unique=True)
    op.create_index(op.f('ix_answer_user_id'), 'answer', ['user_id'], unique=False)
    op.create_table('material_asset',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_material_asset_material_id_material'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_asset'))
    )
    op.create_index(op.f('ix_material_asset_material_id'), 'material_asset', ['material_id'], unique=False)
    op.create_table('material_favorite',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_material_favorite_material_id_material'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_material_favorite_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'material_id', name=op.f('pk_material_favorite'))
    )
    op.create_table('question_template',
    sa.Column('subject_version_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=True),
    sa.Column('ep_award', sa.Integer(), nullable=True),
    sa.Column('ep_wrong', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('test_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_question_template_concept_id_concept'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_question_template_material_id_material'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubric.id'], name=op.f('fk_question_template_rubric_id_rubric'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], name=op.f('fk_question_template_subject_version_id_subject_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], name=op.f('fk_question_template_test_id_test'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_template')),
    sa.UniqueConstraint('subject_version_id', 'key', name=op.f('uq_question_template_subject_version_id'))
    )
    op.create_index(op.f('ix_question_template_concept_id'), 'question_template', ['concept_id'], unique=False)
    op.create_index(op.f('ix_question_template_subject_version_id'), 'question_template', ['subject_version_id'], unique=False)
    op.create_index(op.f('ix_question_template_test_id'), 'question_template', ['test_id'], unique=False)
    op.create_table('tutor_session',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_version_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=True),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_tutor_session_concept_id_concept'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_tutor_session_material_id_material'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], name=op.f('fk_tutor_session_subject_version_id_subject_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_tutor_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutor_session'))
    )
    op.create_index(op.f('ix_tutor_session_user_id'), 'tutor_session', ['user_id'], unique=False)
    op.create_table('tutor_message',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_session.id'], name=op.f('fk_tutor_message_session_id_tutor_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutor_message'))
    )
    op.create_index(op.f('ix_tutor_message_session_id'), 'tutor_message', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_message_session_id'), table_name='tutor_message')
    op.drop_table('tutor_message')
    op.drop_index(op.f('ix_tutor_session_user_id'), table_name='tutor_session')
    op.drop_table('tutor_session')
    op.drop_index(op.f('ix_question_template_test_id'), table_name='question_template')
    op.drop_index(op.f('ix_question_template_subject_version_id'), table_name='question_template')
    op.drop_index(op.f('ix_question_template_concept_id'), table_name='question_template')
    op.drop_table('question_template')
    op.drop_table('material_favorite')
    op.drop_index(op.f('ix_material_asset_material_id'), table_name='material_asset')
    op.drop_table('material_asset')
    op.drop_index(op.f('ix_answer_user_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_item_id'), table_name='answer')
    op.drop_table('answer')
    op.drop_table('user_concept_mastery')
    op.drop_index(op.f('ix_practice_item_session_id'), table_name='practice_item')
    op.drop_table('practice_item')
    op.drop_index(op.f('ix_material_subject_version_id'), table_name='material')
    op.drop_index(op.f('ix_material_concept_id'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_concept_edge_subject_version_id'), table_name='concept_edge')
    op.drop_table('concept_edge')
    op.drop_table('concept_closure')
    op.drop_index(op.f('ix_test_subject_version_id'), table_name='test')
    op.drop_table('test')
    op.drop_index(op.f('ix_rubric_subject_version_id'), table_name='rubric')
    op.drop_table('rubric')
    op.drop_index(op.f('ix_practice_session_user_id'), table_name='practice_session')
    op.drop_table('practice_session')
    op.drop_index(op.f('ix_concept_subject_version_id'), table_name='concept')
    op.drop_index(op.f('ix_concept_key'), table_name='concept')
    op.drop_table('concept')
    op.drop_table('user_subject_progress')
    op.drop_index(op.f('ix_usage_event_user_id'), table_name='usage_event')
    op.drop_table('usage_event')
    op.drop_index(op.f('ix_subject_version_subject_id'), table_name='subject_version')
    op.drop_table('subject_version')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_progression_event_user_id'), table_name='progression_event')
    op.drop_index(op.f('ix_progression_event_subject_id'), table_name='progression_event')
    op.drop_index(op.f('ix_progression_event_seq'), table_name='progression_event')
    op.drop_table('progression_event')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_subject_key'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_season_key'), table_name='season')
    op.drop_table('season')
    op.drop_index(op.f('ix_rank_tier_profile_key'), table_name='rank_tier')
    op.drop_table('rank_tier')
    # ### end Alembic commands ###
