"""ranked duels elo + queue

Revision ID: e5ba6070ebb1
Revises: 51a970b09824
Create Date: 2026-06-26 12:22:28.318291
"""
from alembic import op
import sqlalchemy as sa


revision = 'e5ba6070ebb1'
down_revision = '51a970b09824'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duel_rating',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_duel_rating_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_duel_rating'))
    )
    op.create_table('duel_queue',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_version_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_version_id'], ['subject_version.id'], name=op.f('fk_duel_queue_subject_version_id_subject_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_duel_queue_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_duel_queue'))
    )
    op.create_index(op.f('ix_duel_queue_subject_version_id'), 'duel_queue', ['subject_version_id'], unique=False)
    op.add_column('duel', sa.Column('ranked', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('duel', sa.Column('challenger_rating_delta', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('duel', sa.Column('opponent_rating_delta', sa.Integer(), nullable=False, server_default='0'))
    # defaults handled app-side going forward
    op.alter_column('duel', 'ranked', server_default=None)
    op.alter_column('duel', 'challenger_rating_delta', server_default=None)
    op.alter_column('duel', 'opponent_rating_delta', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duel', 'opponent_rating_delta')
    op.drop_column('duel', 'challenger_rating_delta')
    op.drop_column('duel', 'ranked')
    op.drop_index(op.f('ix_duel_queue_subject_version_id'), table_name='duel_queue')
    op.drop_table('duel_queue')
    op.drop_table('duel_rating')
    # ### end Alembic commands ###
