"""material+test approved_by

Revision ID: f017075767fc
Revises: e5ba6070ebb1
Create Date: 2026-06-30 16:54:45.997878
"""
from alembic import op
import sqlalchemy as sa


revision = 'f017075767fc'
down_revision = 'e5ba6070ebb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('approved_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_material_approved_by_user'), 'material', 'user', ['approved_by'], ['id'], ondelete='SET NULL')
    op.add_column('test', sa.Column('approved_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_test_approved_by_user'), 'test', 'user', ['approved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
    # backfill: existing approved items were self-approved by their creator
    op.execute("UPDATE material SET approved_by = created_by WHERE teacher_approved IS TRUE AND approved_by IS NULL")
    op.execute("UPDATE test SET approved_by = created_by WHERE teacher_approved IS TRUE AND approved_by IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_test_approved_by_user'), 'test', type_='foreignkey')
    op.drop_column('test', 'approved_by')
    op.drop_constraint(op.f('fk_material_approved_by_user'), 'material', type_='foreignkey')
    op.drop_column('material', 'approved_by')
    # ### end Alembic commands ###
